### ISSUE TITLE
Common StaticResourcesInfoProviders

### ISSUE THREAD

**Issue by markjerz** [ZarehD/AspNetStatic#15]
**Is your feature request related to a problem? Please describe.**
It would be nice if you provided some common implementations of IStaticResourcesInfoProvider

**Describe the solution you'd like**
Using blazor ssr to build websites is now a very nice experience. It would be great to support that quickly out of the box. For example,
a `RazorComponentsStaticResourcesInfoProvider` would automatically register all `/page` routes and anything in the `wwwroot` folder would make getting going with AspNetStatic in that use case really great.

**Describe alternatives you've considered**
That may be too restrictive so you could move towards a builder pattern that enables you to quickly configure common patterns in to an overall InfoProvider. For example:

````
var infoProvider = new StaticResourcesInfoProviderBuilder()
    .AddRazorComponentPages()
    .AddWwwRoot()
   .Build();
```

I've not got anything like this working myself yet but happy to contribute back if it seems useful?

**Comment by ZarehD** [comment]
Hello, @markjerz. Thank you for the feedback.

Please take a look at the `StaticResourceInfoProvider` class. Your suggested methods, `AddRazorComponentPages()` and  `AddWebRoot()`, can be implemented as extension method on this class.

Now, while such implementations are inappropriate for the main AspNetStatic project (b/c they're too use-case specific), I will create a "_Community Contributions_" module for them, and create a basic implementation which you and others can use as a basis for contributing your own more complex implementations.

I will update this ticket when that's ready. Thanks again for your feedback.

**Comment by ZarehD** [comment]
Hi @markjerz.

I've update the `StaticResourceInfoProvider` class so it can be used in a fluent style, and added the AspNetStaticContrib package with trivial implementations of the `AddAllProjectRazorPages` and `AddAllWebRootContent` extension methods which you can use as a basis for implementing further refined variations on these themes (and perhaps even contribute back to the community if they're broadly applicable).
