### ISSUE TITLE
Support for embedded url rewrite and hook for custom slug generation 

### ISSUE THREAD

**Issue by mediabuff** [ZarehD/AspNetStatic#4]
Hook for programmatic slug generation

**Comment by ZarehD** [comment]
It appears you are asking for two different features:
 - embedded URL rewrite
 - hook for custom slug generation

Please provide more context & detail about each item. Thanks.

**Comment by mediabuff** [comment]
Yes 
1) inter page URL’s that have dynamic parameters in query string 

2) rewrite urls with slugs replacing Dynamic urls and query parameters

**Comment by ZarehD** [comment]
I'm at a loss... Are you talking about how links in generated static pages are updated to point to other generated static pages? Or is this about the path/name of the generated static page itself? Or is it something else entirely?

It's not clear what you're asking for, and the terse, one-liners are just no help.

Please provide a thorough explanation of each ask with full context and when/where/how it would apply; provide as much detail as possible and give examples if you can. Thank you.

**Comment by mediabuff** [comment]
1) Are you talking about how links in generated static pages are updated to point to other generated static pages? 
Yes, this is the first request. All statically generated pages have the right embedded URLs (replacing the the original dynamic URLS that existed pre-static generation).

2)Or is this about the path/name of the generated static page itself? Or is it something else entirely?
This is the second request. To customize the static URL (for custom slug generation) hook.

**Comment by ZarehD** [comment]
Okay, that's better. Thanks.

You can accomplish what you want by specifying a value for the `PageInfo.OutFile` property instead of letting AspNetStatic construct the disk-file pathname for the generated static file. AspNetStatic converts this pathname into a URI path when updating HREF values.
