### ISSUE TITLE
Typo in GenerateStaticPages() method

### ISSUE THREAD

**Issue by Baka632** [ZarehD/AspNetStatic#7]
**Describe the bug**
There is a typo in the fourth parameter of ```GenerateStaticPages()```

**To Reproduce**
In file [```src/AspNetStatic/StaticPageGeneratorHostExtension.cs```](https://github.com/ZarehD/AspNetStatic/blob/9d07db70ad8209c0ed14ab02292ecd1af5253570/src/AspNetStatic/StaticPageGeneratorHostExtension.cs#L111C16-L111C16)

The fourth parameter is named as `alwaysDefautFile` , this is incorrect. 

**Expected behavior**
The fourth parameter should be named as `alwaysDefaultFile`

**Additional context**
_No_

**Comment by ZarehD** [comment]
Corrected. Thank you.

**Comment by Baka632** [comment]
Well, in another overload of ```GenerateStaticPages()``` , the typo still exists...

![image](https://github.com/ZarehD/AspNetStatic/assets/48171809/ad54fa8a-d63d-4d85-9e41-272828658809)

**Comment by ZarehD** [comment]
Oh snap!

**Comment by ZarehD** [comment]
Used a spellchecker to look for and fix typos across the solution. Thanks again.
